apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::752518105514:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-29T07:00:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1745"
  uid: 3a8a4b7c-00a0-46f2-a519-eaee5f36c15f
data:
  mapUsers: |
    - userarn: arn:aws:iam::752518105514:user/rapa0004  
      username: admin
      groups:
        - system:masters
