apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::752518105514:role/eks-nodegroup-ng-ma-NodeInstanceRole-1GFKA1037E1XO
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-27T10:32:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3531"
  uid: 4a3bd4de-365a-411a-bf74-ed5ec69f2376
data:
  mapUsers: |
    - userarn: arn:aws:iam::752518105514:user/rapa0004  
      username: admin
      groups:
        - system:masters
