# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-0eb5ebf6fd5e14e09:
resource "aws_route_table_association" "rtbassoc-eks-private4" {
  route_table_id = aws_route_table.rtb-eks-private4.id
  subnet_id      = aws_subnet.subnet-eks-private4.id
}

output "rtb-private4-out" {
  value = aws_route_table.rtb-eks-private4.id
}