# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-07b271e3a84d0d94a:
resource "aws_nat_gateway" "nat-eks-public2" {
  allocation_id = aws_eip.eip-nat-eks-public2.id
  subnet_id     = aws_subnet.subnet-eks-public2.id
  tags = {
    "Name" = "ngw-eks-public2"
  }
}
