# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rtbassoc-04310374909657ddd:
resource "aws_route_table_association" "rtbassoc-cicd-private1" {
  route_table_id = aws_route_table.rtb-cicd-private1.id
  subnet_id      = aws_subnet.subnet-cicd-private1.id
}
