# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpc.vpc-vpc-:
resource "aws_vpc" "vpc-eks" {
  assign_generated_ipv6_cidr_block = false
  cidr_block                       = "10.10.0.0/16"
  enable_dns_hostnames             = true
  enable_dns_support               = true
  instance_tenancy                 = "default"
  tags = {
    "Name" = format("eks-%s-cluster", data.aws_ssm_parameter.tf-eks-cluster-name.value)
  }
}

output "vpc-eks-out" {
  value = aws_vpc.vpc-eks.id
}

output "eks-cidr-out" {
  value = aws_vpc.vpc-eks.cidr_block
}
